### ISSUE TITLE
ERROR! 'notify' is not a valid attribute for a Block

### ISSUE THREAD

**Issue by gangyi89** [darkwizard242/cis_ubuntu_2004#11]
# SUMMARY

Am currently experiencing the error when i try to run ansible-playbook <my_playbook>.yml.
Any recommendation on the changes I need to make to allow script to run on ansible 2.9.0?
Thanks!

 # ISSUE TYPE

- Bug Report

# ANSIBLE VERSION

ansible 2.9.0

 # STEPS TO REPRODUCE

1. Clone 1.1.0 branch
2. Run ansible-playbook

**Comment by darkwizard242** [comment]
Hi @gangyi89  - Can you please share the playbook example and the error log? That will help me assess the issue.

**Comment by darkwizard242** [comment]
@gangyi89 - is this still an issue? and if so - can you please share the requested details in the comment above? Otherwise, would like to close out this issue.

**Comment by Halleck45** [comment]
Hi,

There is the log:
```
ERROR! 'notify' is not a valid attribute for a Block

The error appears to be in 'roles/darkwizard242.cis_ubuntu_2004/tasks/section_03.yml': line 860, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: "3.5.3.2.1 | Ensure iptables loopback traffic is configured (Automated)"
  ^ here
```

With Ansible `2.8.3`

**Comment by darkwizard242** [comment]
Hi @Halleck45 - The role at present will require Ansible version 2.10 or greater. 

Apologies, as it looks like I still need to update the required ansible version in the role's metadata.

**Comment by Halleck45** [comment]
Hi,

ok @darkwizard242, thanks

**Comment by darkwizard242** [comment]
Yup. Are we good to close this one @Halleck45 ?

**Comment by anthopark** [comment]
I'm still having the same issue. with the version `2.9.6`. how should I fix this?

**Comment by darkwizard242** [comment]
Hi @anthopark - this role requires Ansible version **2.10** or higher currently.
